name: Node CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: npm install
        run: npm install
      - name: Build
        run: npm run prepare --if-present
      - name: test
        if: success()
        run: npm test
      - name: semantic-release
        if: success() && github.ref == 'refs/heads/master'
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
